{
 "title": "DA5402:A7",
 "description": "This project maintains a dashboard that monitors system statistics\n",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(cpu) (rate(node_cpu_seconds_total{mode=~\"system|user\"}[1m]))",
     "legendFormat": "{{cpu}}"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=~\"system|user\"}[1m]))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes - node_memory_SwapCached_bytes",
     "legendFormat": "Swapped"
    },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Installed" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device!=\"lo\"}[1m])",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device!=\"lo\"}[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Available Disk Storage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(device) (node_filesystem_avail_bytes{device=~\"/dev/nvme0n1p1|/dev/sda6\", mountpoint=~\"/|/boot/efi\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(device) (node_filesystem_free_bytes{device=~\"/dev/nvme0n1p1|/dev/sda6\", mountpoint=~\"/|/boot/efi\"}) / sum by(device) (node_filesystem_size_bytes{device=~\"/dev/nvme0n1p1|/dev/sda6\", mountpoint=~\"/|/boot/efi\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read Activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Write Activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}